export const verifiedSnapshot = {
  verifiedAt: "2026-08-15T19:16:00+08:00",
  northStar: {
    title: "Persistent Personal Agent / JARVIS",
    description:
      "建立一個長期存在、理解目前狀態、能在明確權限下主動協助、執行並驗證結果，且可跨裝置延續並逐步進入實體世界的個人 AI agent。",
    mvjRequiredGates: 8,
    mvjCompletedGates: 0,
    criticalPath: "Issue #1 — PSE → PDA Integration Contract v0.1",
  },
  repositories: [
    {
      key: "umbrella",
      owner: "kodlbegiko",
      repo: "persistent-personal-agent-research",
      label: "Program Control",
      accent: "green",
    },
    {
      key: "pse",
      owner: "kodlbegiko",
      repo: "personal-state-engine-research",
      label: "RT-01 Personal State",
      accent: "blue",
    },
    {
      key: "pda",
      owner: "kodlbegiko",
      repo: "Proactivity-Decision-Algorithm",
      label: "RT-02 Proactivity",
      accent: "purple",
    },
  ],
  tracks: [
    {
      id: "RT-01",
      name: "Personal State",
      subtitle: "個人狀態與證據維護",
      status: "DEVELOPMENT_EVIDENCE",
      stage: 2,
      accent: "green",
      detail: "Candidate-v6 scientific Gate E requirements complete; formal Gate E remains integrity fail-closed. Gate F is not admissible as formal progress in the current lineage.",
    },
    {
      id: "RT-02",
      name: "Proactivity",
      subtitle: "主動介入決策規格",
      status: "PROTECTED_VALIDATION_FAILED",
      stage: 3,
      accent: "blue",
      detail: "Gate B–E passed under the bounded synthetic protocol. Gate F protected/OOD validation reached a terminal FAIL on C5; protected generalization is not established.",
    },
    {
      id: "RT-03",
      name: "Action Verification",
      subtitle: "行動結果驗證與恢復",
      status: "SCOPED",
      stage: 1,
      accent: "violet",
      detail: "Research protocol scoped in Issue #2; implementation and protected evaluation not started.",
    },
    {
      id: "RT-04",
      name: "Long-Horizon",
      subtitle: "跨會話長期連續性",
      status: "NOT_STARTED",
      stage: 0,
      accent: "amber",
      detail: "Blocked on the first closed-loop benchmark.",
    },
    {
      id: "RT-05",
      name: "Multimodal",
      subtitle: "多模態證據 → 狀態",
      status: "NOT_STARTED",
      stage: 0,
      accent: "pink",
      detail: "Requires evidence-to-state policy and closed-loop state mutation semantics.",
    },
    {
      id: "RT-06",
      name: "Cross-device",
      subtitle: "跨裝置一致狀態",
      status: "NOT_STARTED",
      stage: 0,
      accent: "teal",
      detail: "Requires RT-01 state contract and closed-loop MVP.",
    },
    {
      id: "RT-07",
      name: "Physical World",
      subtitle: "實體世界行動能力",
      status: "NOT_STARTED",
      stage: 0,
      accent: "orange",
      detail: "Late-stage research track; high-consequence physical actions remain human-authorized.",
    },
  ],
  gates: [
    {
      track: "RT-02",
      gate: "Gate B",
      verdict: "PASS",
      tone: "pass",
      detail: "Specification consistency and bounded-state audit passed.",
    },
    {
      track: "RT-02",
      gate: "Gate C",
      verdict: "PASS",
      tone: "pass",
      detail: "Oracle and benchmark validity passed under deterministic generated contexts.",
    },
    {
      track: "RT-02",
      gate: "Gate D",
      verdict: "PASS",
      tone: "pass",
      detail: "Baseline evaluation / integrity completed under the frozen protocol.",
    },
    {
      track: "RT-02",
      gate: "Gate E",
      verdict: "PASS",
      tone: "pass",
      detail: "C5 passed the preregistered bounded synthetic validation; this does not establish protected/OOD or real-world generalization.",
    },
    {
      track: "RT-02",
      gate: "Gate F",
      verdict: "FAIL",
      tone: "danger",
      detail: "C5 terminally failed protected/OOD validation: macro-F1 0.0476, 0/24 action-changing protected counterfactual pairs, and an IGNORE-only prediction collapse.",
    },
    {
      track: "RT-01",
      gate: "Gate E (scientific)",
      verdict: "COMPLETE",
      tone: "pass",
      detail: "Candidate-v6 scientific requirements complete.",
    },
    {
      track: "RT-01",
      gate: "Gate E (formal)",
      verdict: "FAIL CLOSED",
      tone: "warn",
      detail: "Historical integrity criterion prevents formal completion in the authoritative current lineage.",
    },
    {
      track: "RT-01",
      gate: "Gate F",
      verdict: "PROHIBITED",
      tone: "danger",
      detail: "Authoritative PR status keeps sealed-final formal progress prohibited pending a legally declared clean-integrity lineage; later branch activity is not counted without admissibility audit.",
    },
  ],
  benchmarks: {
    pse: {
      title: "PSE vs exact A-MEM — adversarial-v7",
      answerable: { candidate: 1.0, baseline: 1.0, metric: "MRR" },
      noEvidence: { candidate: "0 / 30", baseline: "30 / 30", metric: "False retrieval" },
      claim: "Benchmark-specific safety advantage only; overall superiority and SOTA are NOT supported.",
    },
    pda: {
      title: "PDA-SPEC-v2 bounded-state audit",
      values: [
        ["Raw combinations", "62,208"],
        ["Valid states", "41,472"],
        ["Nondeterministic outputs", "0"],
        ["Mandatory invariant violations", "0"],
      ],
      claim: "Specification consistency and bounded Gate-E performance are supported; Gate-F protected/OOD generalization failed and real-world usefulness remains unestablished.",
    },
  },
  blockers: [
    {
      level: "critical",
      title: "PSE → PDA Integration Contract",
      source: "Issue #1",
      text: "尚未 freeze StateSnapshot → InterventionDecision 的正式 contract；因此兩條研究線還不能形成閉環。",
    },
    {
      level: "critical",
      title: "PDA protected/OOD recovery",
      source: "RT-02 Gate F / PR #14",
      text: "C5 在 Gate F terminal FAIL。若要取得 protected generalization evidence，必須建立新的 development/candidate lineage，並在候選者選定後凍結全新的 protected evaluation；既有 Gate-F set 不得用來調參後重複宣稱通過。",
    },
    {
      level: "high",
      title: "Action Verification",
      source: "Issue #2",
      text: "尚未建立『做了動作』與『任務真的成功』之間的驗證層，會阻塞 closed-loop benchmark。",
    },
    {
      level: "high",
      title: "PSE formal integrity lineage",
      source: "RT-01 / PR #2",
      text: "Gate E formal 維持 fail-closed；在合法的新 integrity lineage 完成並通過 admissibility audit 前，不得把 Gate F 當正式進度。",
    },
  ],
  claims: {
    supported: [
      "PSE Candidate-v6 在指定 adversarial-v7 no-evidence subset 的 false retrieval 低於 exact A-MEM。",
      "PDA-SPEC-v2 在已審核 bounded state space 中具 deterministic / invariant consistency evidence。",
      "PDA C5 在 Protocol-v2 Gate E 的 bounded synthetic validation 通過 preregistered criteria。",
      "PDA C5 在 Gate F protected/OOD validation terminal FAIL；此負面結果被保留並限制後續 claim。",
    ],
    notSupported: [
      "PSE is SOTA / universally better than A-MEM.",
      "PDA has protected/OOD generalization or real-world contextual competence.",
      "PDA produces universally correct or human-preferred proactive behavior.",
      "Minimum Viable JARVIS has been achieved.",
    ],
  },
  milestones: [
    { issue: 1, title: "Freeze integration contracts v0.1", track: "Integration", requiredForMvj: true },
    { issue: 2, title: "Action Verification research protocol", track: "RT-03", requiredForMvj: true },
    { issue: 3, title: "First closed-loop integration benchmark", track: "Integration", requiredForMvj: true },
    { issue: 4, title: "Long-horizon continuity benchmark", track: "RT-04", requiredForMvj: true },
    { issue: 5, title: "Multimodal context evidence-to-state", track: "RT-05", requiredForMvj: true },
    { issue: 6, title: "Cross-device continuity", track: "RT-06", requiredForMvj: true },
    { issue: 7, title: "Frontier baseline refresh", track: "Program", requiredForMvj: false },
    { issue: 8, title: "Minimum Viable JARVIS gate", track: "MVJ", requiredForMvj: true },
  ],
  advancementTimeline: {
    version: "1.0",
    rule: "Only terminal/frozen/admissible evidence may create a completed timestamp. Negative terminal evidence is retained rather than erased.",
    phases: [
      {
        id: "phase-0",
        shortLabel: "P0",
        title: "Mission",
        description: "把電影式 JARVIS 願景轉成可驗證的 Persistent Personal Agent 研究任務。",
        nodes: [
          {
            id: "mission-established",
            track: "PROGRAM",
            title: "Persistent Personal Agent Research Mission 建立",
            description: "正式建立總研究 repo，定義 JARVIS-class North Star、研究治理與子研究整合方向。",
            status: "complete",
            achievedAt: "2026-08-14T18:04:32+08:00",
            datePrecision: "time",
            evidenceLabel: "Mission commit 824eb647",
            evidenceUrl: "https://github.com/kodlbegiko/persistent-personal-agent-research/commit/824eb647fa85c7151b72d0b96b09353b76aeb474",
            dependsOn: [],
            requiredForMvj: false,
          },
        ],
      },
      {
        id: "phase-1",
        shortLabel: "P1",
        title: "核心狀態與主動性",
        description: "先讓系統知道『現在什麼是真的』，再建立『現在該不該介入』的可稽核決策層。",
        nodes: [
          {
            id: "pse-gate-e-scientific",
            track: "RT-01",
            title: "PSE Candidate-v6 scientific Gate E 完成",
            description: "Personal State Engine 在 frozen development/protected evidence 上完成 Candidate-v6 scientific selection；形式完整性仍另有 blocker。",
            status: "complete",
            achievedAt: "2026-08-13",
            datePrecision: "date",
            evidenceLabel: "PSE Draft PR #2 authoritative Candidate-v6 terminal",
            evidenceUrl: "https://github.com/kodlbegiko/personal-state-engine-research/pull/2",
            dependsOn: ["PSE benchmark / evaluator / A-MEM comparison"],
            requiredForMvj: true,
            note: "只有日期層級的 authoritative terminal evidence，因此不補猜分鐘級完成時間。",
          },
          {
            id: "pse-integrity-lineage",
            track: "RT-01",
            title: "建立合法的 PSE clean-integrity lineage",
            description: "解決歷史 SEALED-PATH-METADATA-001 導致的 formal Gate E fail-closed；任何 sealed-final 結果必須先通過 admissibility audit。",
            status: "blocked",
            achievedAt: null,
            datePrecision: "date",
            evidenceLabel: "PSE PR #2 integrity boundary",
            evidenceUrl: "https://github.com/kodlbegiko/personal-state-engine-research/pull/2",
            dependsOn: ["PSE Candidate-v6 scientific Gate E"],
            requiredForMvj: true,
            unlockCondition: "在接觸任何新的 protected/sealed surface 前宣告並 freeze 全新 integrity contract / lineage。",
            note: "這是研究完整性 blocker，不會因 branch 上出現 sealed-final workflow 就自動視為解除。",
          },
          {
            id: "pda-gate-b",
            track: "RT-02",
            title: "PDA Gate B — Specification Consistency",
            description: "PDA-SPEC-v2 的 bounded-state exhaustive audit 通過，建立 deterministic、fail-closed 的介入規格。",
            status: "complete",
            achievedAt: "2026-08-14T17:50:36+08:00",
            datePrecision: "time",
            evidenceLabel: "PDA Draft PR #7 terminal Gate-B evidence",
            evidenceUrl: "https://github.com/kodlbegiko/Proactivity-Decision-Algorithm/pull/7",
            dependsOn: [],
            requiredForMvj: true,
          },
          {
            id: "pda-gate-c",
            track: "RT-02",
            title: "PDA Gate C — Oracle / Benchmark Validity",
            description: "benchmark_v2 完成 oracle、leakage、counterfactual、temporal 與 coverage 驗證。",
            status: "complete",
            achievedAt: "2026-08-14T18:42:12+08:00",
            datePrecision: "time",
            evidenceLabel: "PDA Draft PR #8 Gate-C PASS",
            evidenceUrl: "https://github.com/kodlbegiko/Proactivity-Decision-Algorithm/pull/8",
            dependsOn: ["PDA Gate B"],
            requiredForMvj: true,
          },
          {
            id: "pda-gate-d",
            track: "RT-02",
            title: "PDA Gate D — Baseline Integrity",
            description: "凍結並驗證 deterministic comparison baselines，保留失敗 baseline 與 dependency amendment。",
            status: "complete",
            achievedAt: "2026-08-14T21:14:08+08:00",
            datePrecision: "time",
            evidenceLabel: "PDA Draft PR #10 Gate-D PASS",
            evidenceUrl: "https://github.com/kodlbegiko/Proactivity-Decision-Algorithm/pull/10",
            dependsOn: ["PDA Gate C"],
            requiredForMvj: true,
          },
          {
            id: "pda-gate-e",
            track: "RT-02",
            title: "PDA Gate E — Bounded Validation PASS",
            description: "C5_semantic_factor_linear 在凍結 synthetic validation 上通過 preregistered criteria；macro-F1 0.6937，對 B5 delta +0.4791。",
            status: "complete",
            achievedAt: "2026-08-15T18:37:58+08:00",
            datePrecision: "time",
            evidenceLabel: "PDA Draft PR #12 terminal Gate-E PASS",
            evidenceUrl: "https://github.com/kodlbegiko/Proactivity-Decision-Algorithm/pull/12",
            dependsOn: ["PDA Gate D"],
            requiredForMvj: true,
            note: "這個 PASS 只適用於 modeled / synthetic representation，不延伸成 OOD、真人偏好或真實世界能力。",
          },
          {
            id: "pda-gate-f",
            track: "RT-02",
            title: "PDA Gate F — Protected / OOD Validation",
            description: "C5 在一次性 protected set 上失敗：macro-F1 0.0476，預測 collapse 為 IGNORE=120，action-changing counterfactual 0/24。",
            status: "failed",
            terminalAt: "2026-08-15T19:10:09+08:00",
            datePrecision: "time",
            evidenceLabel: "PDA Draft PR #14 terminal Gate-F FAIL",
            evidenceUrl: "https://github.com/kodlbegiko/Proactivity-Decision-Algorithm/pull/14",
            dependsOn: ["PDA Gate E"],
            requiredForMvj: true,
            note: "這個 protected set 已退休為 C5 confirmatory evidence；不得拿來調 C5 後再重複宣稱 Gate F PASS。",
          },
          {
            id: "pda-recovery",
            track: "RT-02",
            title: "PDA Protected/OOD Recovery Lineage",
            description: "若要補齊可信主動性，需要新的 development/candidate lineage，再於候選者固定後建立全新的 protected evaluation。",
            status: "blocked",
            achievedAt: null,
            datePrecision: "date",
            evidenceLabel: "Gate-F terminal recovery rule",
            evidenceUrl: "https://github.com/kodlbegiko/Proactivity-Decision-Algorithm/pull/14",
            dependsOn: ["Gate F negative result preserved"],
            requiredForMvj: true,
            unlockCondition: "建立新 candidate lineage，且 fresh protected set 必須在新候選者 freeze 後才產生。",
          },
        ],
      },
      {
        id: "phase-2",
        shortLabel: "P2",
        title: "第一個可信閉環",
        description: "把 PSE 與 PDA 接起來，再加入執行結果驗證，形成 State → Decision → Action → Verification → State。",
        nodes: [
          {
            id: "integration-contract",
            track: "INTEGRATION",
            title: "Freeze PSE → PDA Integration Contract v0.1",
            description: "正式定義 StateSnapshot、InterventionDecision、ActionAttempt、VerificationRecord，以及 disputed/no-evidence 的 fail-closed semantics。",
            status: "current",
            achievedAt: null,
            datePrecision: "date",
            issue: 1,
            dependsOn: ["RT-01 state semantics", "RT-02 bounded decision semantics"],
            requiredForMvj: true,
            unlockCondition: "完成 Issue #1 acceptance checklist 並 freeze contract identity。",
            note: "這是目前 umbrella architecture 的 critical path；PDA protected/OOD recovery 仍需平行處理。",
          },
          {
            id: "action-verification",
            track: "RT-03",
            title: "Action Verification 取得 development evidence",
            description: "證明 agent 不只『做了動作』，還能驗證目標真的完成，並處理 inconclusive / recovery / rollback。",
            status: "future",
            achievedAt: null,
            datePrecision: "date",
            issue: 2,
            dependsOn: ["Integration Contract v0.1"],
            requiredForMvj: true,
            unlockCondition: "Issue #2 protocol + implementation + development evidence。",
          },
          {
            id: "closed-loop-benchmark",
            track: "INTEGRATION",
            title: "First Closed-loop Integration Benchmark",
            description: "第一次完整驗證 State → Proactivity → Action → Verification → State Update 的可重現閉環。",
            status: "future",
            achievedAt: null,
            datePrecision: "date",
            issue: 3,
            dependsOn: ["Integration Contract v0.1", "RT-03 Action Verification", "admissible proactivity policy"],
            requiredForMvj: true,
            unlockCondition: "Issue #3 benchmark freeze、execution、verification 與 fail-closed result。",
          },
        ],
      },
      {
        id: "phase-3",
        shortLabel: "P3",
        title: "長期連續與環境感知",
        description: "讓 agent 從單次閉環進化到跨時間、跨感官、跨裝置的持續存在。",
        nodes: [
          {
            id: "long-horizon",
            track: "RT-04",
            title: "Long-Horizon Continuity",
            description: "跨會話、跨天持續追蹤任務、依賴、等待與重新規劃，而不遺失限制或提早宣告完成。",
            status: "future",
            achievedAt: null,
            datePrecision: "date",
            issue: 4,
            dependsOn: ["First Closed-loop Benchmark"],
            requiredForMvj: true,
            unlockCondition: "Issue #4 protected long-horizon continuity evidence。",
          },
          {
            id: "multimodal",
            track: "RT-05",
            title: "Multimodal Context → Trusted State",
            description: "把視覺、語音、螢幕與事件等多模態觀察轉成有 provenance、confidence 與更新規則的 world/personal state。",
            status: "future",
            achievedAt: null,
            datePrecision: "date",
            issue: 5,
            dependsOn: ["Closed-loop state mutation semantics"],
            requiredForMvj: true,
            unlockCondition: "Issue #5 evidence-to-state policy + benchmark。",
          },
          {
            id: "cross-device",
            track: "RT-06",
            title: "Cross-device Continuity",
            description: "Mac、手機、穿戴裝置共享同一可信 state 與 action history，而不是各自形成互相衝突的 AI。",
            status: "future",
            achievedAt: null,
            datePrecision: "date",
            issue: 6,
            dependsOn: ["RT-01 state contract", "Closed-loop agent"],
            requiredForMvj: true,
            unlockCondition: "Issue #6 consistency / conflict / handoff evidence。",
          },
        ],
      },
      {
        id: "phase-4",
        shortLabel: "P4",
        title: "Minimum Viable JARVIS",
        description: "第一個可被嚴格驗收的整合式 Persistent Personal Agent，而不是只看起來像 JARVIS 的 demo。",
        nodes: [
          {
            id: "mvj",
            track: "MVJ",
            title: "Minimum Viable JARVIS Gate",
            description: "整合 persistent state、proactivity、action verification、long-horizon、multimodal 與 cross-device 的最低可信版本。",
            status: "future",
            achievedAt: null,
            datePrecision: "date",
            issue: 8,
            dependsOn: ["Issues #1–#6 required evidence", "PDA protected recovery or equivalent admissible robustness evidence"],
            requiredForMvj: true,
            unlockCondition: "Issue #8 的所有 acceptance criteria 以 admissible evidence 通過。",
          },
        ],
      },
      {
        id: "phase-5",
        shortLabel: "P5",
        title: "Physical World → North Star",
        description: "MVJ 之後再把可信 agent 延伸到穿戴式與實體世界；高後果行動維持人類授權。",
        nodes: [
          {
            id: "physical-world",
            track: "RT-07",
            title: "Physical World Agent Evidence",
            description: "讓 agent 能安全地理解並控制可驗證的實體裝置／機器人任務，包含權限、失敗偵測與人類介入邊界。",
            status: "future",
            achievedAt: null,
            datePrecision: "date",
            dependsOn: ["Minimum Viable JARVIS"],
            requiredForMvj: false,
            unlockCondition: "RT-07 development → protected validation evidence。",
          },
          {
            id: "north-star",
            track: "NORTH STAR",
            title: "JARVIS-class Persistent Personal Agent",
            description: "長期存在、理解你與環境、知道何時介入、能執行並驗證、跨裝置延續，且在安全授權下逐步進入實體世界。",
            status: "future",
            achievedAt: null,
            datePrecision: "date",
            dependsOn: ["MVJ", "RT-07", "independent reproduction / real-world reliability / safety evidence"],
            requiredForMvj: false,
            unlockCondition: "North Star acceptance criteria 必須以跨場景、可重現、可稽核 evidence 達成，而非單一 demo。",
          },
        ],
      },
    ],
  },
};

export const maturityStages = [
  "NOT_STARTED",
  "SCOPED",
  "DEVELOPMENT_EVIDENCE",
  "PROTECTED_VALIDATION",
  "VALIDATED",
  "INTEGRATED",
  "INDEPENDENTLY_REPRODUCED",
];
