
import { test, expect } from '@playwright/test';
const viewports = [{ width:1470,height:956 },{ width:1512,height:982 },{ width:1280,height:800 },{ width:390,height:844 }];
async function mockPulse(page) { await page.route('**/api/research-pulse', (route) => route.fulfill({ status:200, headers:{'content-type':'application/json'}, body:JSON.stringify({ status:'LIVE', fetchedAt:new Date().toISOString(), source:'test', events:[] }) })); }
for (const viewport of viewports) for (const lang of ['zh-Hant','en']) test('responsive '+viewport.width+'x'+viewport.height+' '+lang, async ({ page }) => { await page.setViewportSize(viewport); await mockPulse(page); await page.goto('/?lang='+lang); await expect(page.locator('body')).toBeVisible(); const overflow = await page.evaluate(() => document.documentElement.scrollWidth - document.documentElement.clientWidth); expect(overflow).toBeLessThanOrEqual(1); await expect(page.locator('.control-plane-v2')).toBeVisible(); await expect(page.locator('.live-pulse-v2')).toBeVisible(); await expect(page.locator('#history')).toBeVisible(); });

test('verified history exposes dated phases, filters, and roadmap handoff', async ({ page }) => { await mockPulse(page); await page.goto('/?lang=zh-Hant'); const history = page.locator('#history'); await expect(history).toBeVisible(); await expect(history).toContainText('研究歷史與階段進入時間'); await expect(history).toContainText('P0'); await expect(history).toContainText('P1'); await expect(history).toContainText('首次可驗證事件'); await history.getByRole('button', { name: 'RT-02' }).click(); await expect(history).toContainText('Gate F'); const openRoadmap = history.getByRole('button', { name: /開啟完整北極星路徑/ }); await openRoadmap.click(); await expect(page.getByRole('dialog', { name: /從現在走到北極星/ })).toBeVisible(); });

test('roadmap keyboard dialog and focus return', async ({ page }) => { await mockPulse(page); await page.goto('/?lang=zh-Hant'); const launcher = page.locator('.roadmap-launcher'); await launcher.click(); const dialog = page.locator('[role="dialog"]').filter({ has: page.locator('#roadmap-title') }); await expect(dialog).toBeVisible(); await page.keyboard.press('Escape'); await expect(dialog).toBeHidden(); await expect(launcher).toBeFocused(); });

test('lineage detail is accessible and PSE clean stays pending', async ({ page }) => { await mockPulse(page); await page.goto('/?lang=en'); const button = page.getByRole('button', { name: /personal-state-engine-clean-integrity/i }); await button.click(); const dialog = page.getByRole('dialog', { name: /personal-state-engine-clean-integrity/i }); await expect(dialog).toContainText('PENDING'); await expect(dialog).toContainText('NATURALISTIC_EXTERNAL_VALIDITY_INFRASTRUCTURE_BLOCKED'); await page.keyboard.press('Escape'); await expect(dialog).toBeHidden(); });

test('GitHub/live failure never removes verified dashboard', async ({ page }) => { await page.route('**/api/research-pulse', (route) => route.fulfill({ status:503, body:'{}' })); await page.route('https://api.github.com/**', (route) => route.abort()); await page.route('**/live-events.json', (route) => route.fulfill({ status:200, contentType:'application/json', body:JSON.stringify({ fetchedAt:new Date().toISOString(),source:'test-fallback',events:[] }) })); await page.goto('/?lang=en'); await expect(page.locator('#root')).toBeVisible(); await expect(page.getByText(/Persistent Personal Agent/i).first()).toBeVisible(); });

test('gate and blocker content rails remain aligned', async ({ page }) => { await mockPulse(page); await page.setViewportSize({width:1470,height:956}); await page.goto('/?lang=zh-Hant'); const gates = await page.locator('#gates').boundingBox(); const blockers = await page.locator('#blockers').boundingBox(); if (gates && blockers) expect(Math.abs(gates.x - blockers.x)).toBeLessThanOrEqual(4); });
