
import { useEffect, useMemo, useRef, useState } from 'react';
import registry from '../../dashboard/state/registry/research-lineages.json';
import { useLanguage } from '../i18n.jsx';

function localized(value, language) { if (value == null) return '—'; if (typeof value === 'string') return value; return language === 'en' ? value.en : value.zh; }
function format(value, locale) { if (!value) return '—'; const date = new Date(value); if (Number.isNaN(date.getTime())) return value; return new Intl.DateTimeFormat(locale, { timeZone: 'Asia/Taipei', year: 'numeric', month: '2-digit', day: '2-digit', hour: '2-digit', minute: '2-digit', hour12: false }).format(date); }

const text = {
  'zh-Hant': { eyebrow: 'RESEARCH CONTROL PLANE V2', title: '可重建的已驗證狀態', history: 'Verified History', audit: 'Since Last Verified Audit', visit: 'Since Your Last Visit', registry: 'Research Lineage Registry', policy: 'Watch Policy', snapshot: 'Snapshot', fresh: 'VERIFIED', stale: 'STALE VERIFIED SNAPSHOT', detail: 'Lineage 詳情', close: '關閉', current: 'CURRENT', latest: 'LATEST VERIFIED EVENT', refs: 'ACTIVE BRANCH / PR', gates: 'GATES', terminal: 'TERMINAL HISTORY', blockers: 'BLOCKERS', next: 'NEXT TARGET', evidence: 'EVIDENCE', claim: 'CLAIM BOUNDARY', lastAudit: 'LAST AUDIT', live: 'LIVE ACTIVITY', none: '無', firstVisit: '這是此瀏覽器首次看到這份 snapshot。' },
  en: { eyebrow: 'RESEARCH CONTROL PLANE V2', title: 'Reconstructable verified state', history: 'Verified History', audit: 'Since Last Verified Audit', visit: 'Since Your Last Visit', registry: 'Research Lineage Registry', policy: 'Watch Policy', snapshot: 'Snapshot', fresh: 'VERIFIED', stale: 'STALE VERIFIED SNAPSHOT', detail: 'Lineage detail', close: 'Close', current: 'CURRENT', latest: 'LATEST VERIFIED EVENT', refs: 'ACTIVE BRANCH / PR', gates: 'GATES', terminal: 'TERMINAL HISTORY', blockers: 'BLOCKERS', next: 'NEXT TARGET', evidence: 'EVIDENCE', claim: 'CLAIM BOUNDARY', lastAudit: 'LAST AUDIT', live: 'LIVE ACTIVITY', none: 'None', firstVisit: 'This is the first time this browser has seen this snapshot.' }
};

export default function ControlPlaneMetaPanel() {
  const { language, locale, snapshot } = useLanguage(); const l = text[language] || text.en;
  const [selected, setSelected] = useState(null); const [live, setLive] = useState(null); const dialogRef = useRef(null); const triggerRef = useRef(null);
  const seenKey = 'jarvis-control-plane:lastSeenSnapshotId'; const previousSeen = (() => { try { return localStorage.getItem(seenKey); } catch { return null; } })();
  const stale = Date.now() - Date.parse(snapshot.verifiedAt) > (snapshot.controlPlane?.staleAfterHours || 2) * 3600000;
  useEffect(() => { try { localStorage.setItem(seenKey, snapshot.snapshotId); } catch {} }, [snapshot.snapshotId]);
  useEffect(() => { const handler = (event) => setLive(event.detail); window.addEventListener('jarvis:live-pulse-state', handler); return () => window.removeEventListener('jarvis:live-pulse-state', handler); }, []);
  useEffect(() => { if (!selected) return; const previous = document.body.style.overflow; document.body.style.overflow = 'hidden'; setTimeout(() => dialogRef.current?.querySelector('button')?.focus(), 0); const key = (event) => { if (event.key === 'Escape') setSelected(null); if (event.key !== 'Tab') return; const focusable = [...(dialogRef.current?.querySelectorAll('button,a[href]') || [])]; if (!focusable.length) return; if (event.shiftKey && document.activeElement === focusable[0]) { event.preventDefault(); focusable.at(-1).focus(); } else if (!event.shiftKey && document.activeElement === focusable.at(-1)) { event.preventDefault(); focusable[0].focus(); } }; window.addEventListener('keydown', key); return () => { document.body.style.overflow = previous; window.removeEventListener('keydown', key); setTimeout(() => triggerRef.current?.focus(), 0); }; }, [selected]);
  const lineage = selected ? registry.lineages.find((item) => item.id === selected) : null;
  const line = useMemo(() => { if (!lineage) return null; if (lineage.id === 'program-control') return snapshot.researchLines?.find((item) => item.id === 'program-integration'); if (lineage.id === 'pda') return snapshot.researchLines?.find((item) => item.id === 'pda-lineage'); if (lineage.id === 'pare') return snapshot.researchLines?.find((item) => item.id === 'pare-lineage'); if (lineage.id === 'pse-clean-integrity') return snapshot.researchLines?.find((item) => item.id === 'pse-clean-lineage'); return snapshot.researchLines?.find((item) => item.id === 'pse-lineage'); }, [lineage, snapshot]);
  const gates = lineage ? (snapshot.gates || []).filter((gate) => gate.track === lineage.track) : [];
  const blockers = lineage ? (snapshot.blockers || []).filter((item) => String(item.source || '').includes(lineage.track) || String(item.title || '').toLowerCase().includes(lineage.repo.split('-')[0])) : [];
  const latestHistory = line?.history?.at(-1);
  const sinceVisit = previousSeen && previousSeen !== snapshot.snapshotId ? snapshot.controlPlane?.changesSincePrevious || [] : [];
  return <section className="control-plane-v2" id="verified-history">
    <header className="control-plane-head"><div><span>{l.eyebrow}</span><h2>{l.title}</h2></div><strong className={stale ? 'is-stale' : 'is-fresh'}>{stale ? l.stale : l.fresh}</strong></header>
    <div className="control-plane-identities"><div><span>{l.snapshot}</span><strong>{snapshot.snapshotId}</strong><small>{snapshot.contentHash}</small></div><div><span>{l.policy}</span><strong>v{snapshot.controlPlane?.watchPolicyVersion}</strong><small>{snapshot.controlPlane?.watchPolicyHash}</small></div><div><span>{l.registry}</span><strong>{snapshot.controlPlane?.registryVersion}</strong><small>{registry.lineages.length} lineages</small></div></div>
    <div className="control-plane-columns"><article><h3>{l.audit}</h3>{(snapshot.controlPlane?.changesSincePrevious || []).map((change, index) => <p key={index}><span aria-hidden="true">{change.type === 'terminal' ? '×' : change.type === 'lineage' ? '+' : '↻'}</span>{localized(change, language)}</p>)}</article><article><h3>{l.visit}</h3>{sinceVisit.length ? sinceVisit.map((change, index) => <p key={index}><span aria-hidden="true">+</span>{localized(change, language)}</p>) : <p>{l.firstVisit}</p>}</article></div>
    <div className="verified-history-list"><h3>{l.history}</h3>{(snapshot.controlPlane?.history || []).map((item) => <div key={item.snapshotId}><strong>{item.snapshotId}</strong><span>{format(item.verifiedAt, locale)}</span><code>{String(item.sourceUmbrellaSHA).slice(0, 12)}</code><small>{item.auditId}</small></div>)}</div>
    <div className="registry-grid"><h3>{l.registry}</h3>{registry.lineages.map((item) => <button key={item.id} ref={selected === item.id ? triggerRef : null} type="button" onClick={(event) => { triggerRef.current = event.currentTarget; setSelected(item.id); }}><span>{item.track} · {item.role}</span><strong>{item.repo}</strong><small>{item.watchState} · {item.admissibility}</small></button>)}</div>
    {lineage ? <div className="lineage-backdrop" onMouseDown={(event) => { if (event.target === event.currentTarget) setSelected(null); }}><section ref={dialogRef} className="lineage-dialog" role="dialog" aria-modal="true" aria-labelledby="lineage-detail-title"><header><div><span>{l.detail}</span><h2 id="lineage-detail-title">{lineage.repo}</h2><p>{lineage.watchState} · {lineage.admissibility}</p></div><button type="button" onClick={() => setSelected(null)} aria-label={l.close}>×</button></header><div className="lineage-detail-grid">
      <article><h3>{l.current}</h3><p>{localized(line?.current, language)}</p></article><article><h3>{l.latest}</h3><p>{latestHistory ? localized(latestHistory, language) : l.none}</p><small>{format(latestHistory?.at || line?.latestAt, locale)}</small></article><article><h3>{l.refs}</h3>{lineage.activeRefs.map((ref, index) => <p key={index}><code>{ref.branch || ref.name}</code><br/><small>{ref.sha}</small></p>)}</article><article><h3>{l.gates}</h3>{gates.length ? gates.map((gate) => <p key={gate.gate}><strong>{gate.gate}</strong> · {gate.verdict}</p>) : <p>{l.none}</p>}</article><article><h3>{l.terminal}</h3>{line?.history?.filter((item) => ['failed','blocked'].includes(item.status)).slice(-4).map((item, index) => <p key={index}>{localized(item, language)}</p>) || <p>{l.none}</p>}</article><article><h3>{l.blockers}</h3>{blockers.length ? blockers.map((item, index) => <p key={index}>{item.title}</p>) : <p>{l.none}</p>}</article><article><h3>{l.next}</h3><p>{localized(line?.next, language)}</p></article><article><h3>{l.evidence}</h3><a href={lineage.sourceOfTruth} target="_blank" rel="noreferrer">{lineage.sourceOfTruth}</a></article><article><h3>{l.claim}</h3><p>{localized(lineage.claimBoundary, language)}</p></article><article><h3>{l.lastAudit}</h3><p>{format(snapshot.verifiedAt, locale)}</p><code>{snapshot.auditId}</code></article><article><h3>{l.live}</h3><p>{live?.status || '—'}</p><small>{live?.source || l.none}</small></article>
    </div></section></div> : null}
  </section>;
}
